"""add phone number to users table

Revision ID: ccb13ca40cf1
Revises: 
Create Date: 2022-11-07 11:44:43.309086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccb13ca40cf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('posts', 'user_id',
                    existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key('post_users_fk', source_table='posts', referent_table='users',
                          local_cols=['user_id'], remote_cols=['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_constraint('post_users_fk', 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts',
                          'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
